'use client';
import { dashboardActionPrimary,dashboardField } from '@/components/shared/dashboard-action-styles';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
export type WorkspaceField={name:string;label:string;type?:'text'|'email'|'textarea'|'datetime-local'|'select';options?:readonly string[];minLength?:number;maxLength?:number};
export function WorkspaceForm({action,values={},fields=[],label='Save',redirectTo}:{action:string;values?:Record<string,unknown>;fields?:WorkspaceField[];label?:string;redirectTo?:string}){
 const router=useRouter();const [pending,setPending]=useState(false);const [message,setMessage]=useState('');const [token,setToken]=useState('');
 return <form className="space-y-4" onSubmit={async event=>{event.preventDefault();if(pending)return;const form=event.currentTarget;const data=new FormData(form);const body:Record<string,unknown>={...values,action};for(const field of fields)body[field.name]=data.get(field.name);if(body.due)body.due=new Date(String(body.due)).toISOString();setPending(true);setMessage('');try{const response=await fetch('/api/workspaces',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to save.');if(result.token){setToken(result.token);setMessage('Invitation created. Copy the code below and share it privately with the intended recipient.');}else{setMessage('Saved.');form.reset();if(redirectTo)router.push(redirectTo);router.refresh();}}catch(error){setMessage(error instanceof Error?error.message:'Unable to save.');}finally{setPending(false);}}}>
 {fields.map(field=><label key={field.name} className="block text-sm font-semibold">{field.label}{field.type==='textarea'?<textarea name={field.name} required minLength={field.minLength??10} maxLength={field.maxLength??4000} rows={5} className={dashboardField}/>:field.type==='select'?<select name={field.name} className={dashboardField}>{field.options?.map(value=><option key={value}>{value}</option>)}</select>:<input name={field.name} required type={field.type??'text'} minLength={field.minLength??3} maxLength={field.maxLength??160} className={dashboardField}/>}</label>)}
 <button disabled={pending} className={dashboardActionPrimary}>{pending?'Saving…':label}</button><p role="status" className="text-sm text-[#5f6555]">{message}</p>{token?<div className="rounded-xl bg-[#f7f8f2] p-3"><label className="text-sm">Private invitation code<input readOnly value={token} className="mt-2 w-full rounded border p-2 font-mono text-xs" onFocus={event=>event.currentTarget.select()}/></label><p className="mt-2 text-xs text-[#6c7162]">Expires in seven days. Recipient enters it at Dashboard → Workspaces → Accept invitation. It is shown only here.</p></div>:null}
 </form>;
}
