import Link from 'next/link';
import { classroomDetail,assignmentQuestionChoices } from '@education/database/learning-workspaces';
import { workspaceSession } from '@/lib/workspaces';
import { WorkspaceLayout } from '@/components/workspaces/workspace-layout';
import { WorkspaceForm } from '@/components/workspaces/workspace-form';
import { AssignmentBuilder } from '@/components/workspaces/assignment-builder';
import { Panel } from '@/components/app-shell/dashboard-ui';
export const metadata={title:'Educator classroom'};
export default async function Page({params}:{params:Promise<{id:string}>}){const {id}=await params;const {user,actor}=await workspaceSession();const data=await classroomDetail(actor,id,true);const questions=await assignmentQuestionChoices(actor);return <WorkspaceLayout user={user} title={data.room.title} description="Manage your classroom roster and assignments. Results from unrelated practice remain private."><Panel title="Invite a learner" description="The invitation is bound to the learner's verified email and expires in seven days."><WorkspaceForm action="invite.create" values={{kind:'classroom',classroomId:id}} fields={[{name:'email',label:'Learner email',type:'email',maxLength:254}]} label="Create invitation"/></Panel><Panel title={`Roster (${data.roster.length}/100)`}>{data.roster.map(member=><div key={member.id} className="mb-4 rounded-xl border p-4"><p className="mb-3 break-words text-sm">{member.name||'Learner'} · {member.email}</p><WorkspaceForm action="classroom.remove" values={{id,userId:member.id}} label="Remove learner"/></div>)}</Panel><Panel title="Recent invitations">{data.invites.map(invite=><div key={invite.id} className="mb-3 rounded-xl border p-3"><p className="mb-2 break-words text-sm">{invite.email} · {invite.usedAt?'Accepted':invite.revokedAt?'Revoked':invite.expiresAt<=new Date()?'Expired':'Pending'}</p>{!invite.usedAt&&!invite.revokedAt?<WorkspaceForm action="invite.revoke" values={{id:invite.id}} label="Revoke invitation"/>:null}</div>)}</Panel><Panel title="Create assignment" description="Questions are pinned to reviewed versions. Future editorial changes do not change existing assignments."><AssignmentBuilder classroomId={id} questions={questions}/></Panel><Panel title="Assignments and submitted results" action={<Link className="text-sm underline" href={`/dashboard/workspaces/educator/${id}/export-csv`}>Download gradebook CSV</Link>}>{data.assignments.map(a=><div key={a.id} className="mb-5 rounded-xl border p-4"><h2 className="font-bold">{a.title}</h2><p className="my-2 text-sm">{a.exam} · Due {a.dueAt.toISOString()} · {a.closedAt?'Closed':'Open'}</p>{data.roster.map(member=>{const work=data.work.find(w=>w.assignmentId===a.id&&w.userId===member.id);return <p key={member.id} className="mb-2 text-sm text-slate-600">{member.name||member.email}: {work?.submittedAt?`${work.percentage}% correct`:work?'Started':'Not started'}</p>;})}{!a.closedAt?<WorkspaceForm action="assignment.close" values={{id:a.id}} label="Close assignment"/>:null}</div>)}</Panel><Panel title="Archive classroom" description="Archiving ends learner access and disables invitations. This action cannot be undone from this screen."><WorkspaceForm action="classroom.archive" values={{id}} label="Archive classroom" redirectTo="/dashboard/workspaces"/></Panel></WorkspaceLayout>;}
