"use client";
import { useState } from 'react';
import Link from 'next/link';
import { allocateStudyMinutes, type StudySubject } from '@/lib/public/planning';
import { downloadText } from '@/lib/public/download';

export function StudyPlanner() {
  const [minutes, setMinutes] = useState('300');
  const [subjects, setSubjects] = useState<StudySubject[]>([{ name: 'Math', weight: 3 }, { name: 'Reading', weight: 2 }]);
  const [result, setResult] = useState<ReturnType<typeof allocateStudyMinutes> | null>(null);
  const [error, setError] = useState('');
  function update(index: number, patch: Partial<StudySubject>) { setSubjects(subjects.map((s, i) => i === index ? { ...s, ...patch } : s)); setResult(null); }
  return <section className="public-panel"><h2>Build your weekly allocation</h2><p>Priority is a relative weight: 4 gets twice the time of 2. Reserve breaks separately. This plan stays on this page until you download it.</p><form onSubmit={e => { e.preventDefault(); try { setResult(allocateStudyMinutes(Number(minutes), subjects)); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Check your inputs.'); setResult(null); } }}><label className="public-field">Available study minutes per week<input type="number" min="15" max="10080" step="1" value={minutes} onChange={e => {setMinutes(e.target.value);setResult(null);}} required /></label>{subjects.map((subject, index) => <div className="planner-row" key={index}><label className="public-field">Subject {index + 1}<input maxLength={80} required value={subject.name} onChange={e => update(index, { name: e.target.value })} /></label><label className="public-field">Priority (1–5)<input type="number" min="1" max="5" step="1" required value={subject.weight || ''} onChange={e => update(index, { weight: Number(e.target.value) })} /></label><button className="button button--secondary" type="button" disabled={subjects.length === 1} aria-label={`Remove subject ${index + 1}`} onClick={() => {setSubjects(subjects.filter((_, i) => i !== index));setResult(null);}}>Remove</button></div>)}<div className="public-actions"><button type="button" className="button button--secondary" disabled={subjects.length >= 12} onClick={() => {setSubjects([...subjects,{name:'',weight:1}]);setResult(null);}}>Add subject</button><button className="button button--primary" type="submit">Calculate plan</button></div></form><p role="alert">{error}</p>{result && <div className="public-result" aria-live="polite"><h3>Your weekly plan</h3><ul>{result.map((r,i) => <li key={i}><strong>{r.name}</strong>: {r.minutes} minutes</li>)}</ul><p>Total: {result.reduce((sum,r) => sum+r.minutes,0)} minutes. Split each allocation into manageable sessions and review after a week.</p><button className="button button--secondary" onClick={() => downloadText('weekly-study-plan.txt', 'Weekly study plan\n'+result.map(r => `${r.name}: ${r.minutes} minutes`).join('\n')+'\nPriority-weighted allocation; breaks excluded.\n')}>Download plan</button></div>}<p>For saved goals and session tracking, <Link href="/dashboard/study-plan">open your account study plan</Link>.</p></section>;
}
