import Link from 'next/link';
import { assignmentSession } from '@education/database/learning-workspaces';
import { workspaceSession } from '@/lib/workspaces';
import { WorkspaceLayout } from '@/components/workspaces/workspace-layout';
import { AssignmentRunner } from '@/components/workspaces/assignment-runner';
import { WorkspaceForm } from '@/components/workspaces/workspace-form';
import { Panel } from '@/components/app-shell/dashboard-ui';
export const metadata={title:'Classroom assignment'};
export default async function Page({params}:{params:Promise<{id:string}>}){const {id}=await params;const {user,actor}=await workspaceSession();const data=await assignmentSession(actor,id);return <WorkspaceLayout user={user} title={data.assignment.title} description={`${data.assignment.exam} · Due ${data.assignment.dueAt.toISOString()} · Save a draft or submit within four hours of starting.`}>{data.work?.submittedAt?<Panel title="Assignment submitted"><p className="text-lg font-bold">{data.work.percentage}% correct</p><p className="my-3 text-sm text-slate-600">This is practice performance, not an official exam score.</p>{data.work.attemptId?<Link className="text-sm underline" href={`/dashboard/test-prep/practice/history/${data.work.attemptId}`}>Review your answers</Link>:<p className="text-sm">The saved review was deleted. Your submitted score remains in this classroom.</p>}</Panel>:!data.work||data.expired?<Panel title={data.work?'Session expired':'Start assignment'}><p className="mb-4 text-sm text-slate-600">Start a four-hour session. Restarting an expired session clears its saved draft.</p><WorkspaceForm action="assignment.start" values={{id}} label={data.work?'Restart assignment':'Start assignment'}/></Panel>:<AssignmentRunner id={id} questions={data.questions} initialAnswers={data.work.draftAnswers}/>}</WorkspaceLayout>;}
