"use client";
import { useState } from "react";
import { buildPracticePlan, formatPracticePlanCsv, formatPracticePlanText, PRACTICE_TOPICS, type ExamKind } from "@/app/dashboard/test-prep/practice-plan";
import { ThemedExportSelect } from "@/components/shared/themed-export-select";
const action = "inline-flex min-h-10 items-center justify-center rounded-full border border-slate-200 bg-white px-4 text-xs font-bold text-slate-900 hover:border-violet-400 hover:bg-violet-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-600";
function download(text: string, filename: string, mime: string) { const url = URL.createObjectURL(new Blob([text], { type: mime })); const link = document.createElement("a"); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
export function ExamPracticePlanner() {
  const [exam, setExam] = useState<ExamKind>("SAT");
  const [days, setDays] = useState(7);
  const [capacity, setCapacity] = useState(60);
  const [ids, setIds] = useState<string[]>(PRACTICE_TOPICS.filter(t => t.exam === "SAT" || t.exam === "Both").map(t => t.id));
  const [feedback, setFeedback] = useState("");
  const topics = PRACTICE_TOPICS.filter(t => t.exam === exam || t.exam === "Both");
  const plan = buildPracticePlan(exam, ids, days, capacity);
  function changeExam(next: ExamKind) { setExam(next); setIds(PRACTICE_TOPICS.filter(t => t.exam === next || t.exam === "Both").map(t => t.id)); setFeedback(""); }
  return <section aria-label="Exam practice planner" className="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
    <div><h2 className="text-lg font-extrabold text-slate-950">Personal practice planner</h2><p className="mt-1 text-sm text-slate-600">Build a realistic SAT or ACT practice schedule. No practice is recorded or scored by this planner.</p></div>
    <div className="flex flex-wrap gap-2" role="group" aria-label="Choose exam">{(["SAT", "ACT"] as const).map(item => <button type="button" key={item} onClick={() => changeExam(item)} aria-pressed={exam === item} className={`${action} ${exam === item ? "!border-slate-900 !bg-slate-900 !text-white" : ""}`}>{item}</button>)}</div>
    <div className="flex flex-wrap gap-4"><ThemedExportSelect name="practiceDays" label="Planning horizon" defaultValue="7" value={String(days)} onValueChange={v => setDays(Number(v))} options={[3, 5, 7, 10, 14, 21, 30].map(n => ({ value: String(n), label: `${n} days` }))} /><ThemedExportSelect name="practiceCapacity" label="Daily capacity" defaultValue="60" value={String(capacity)} onValueChange={v => setCapacity(Number(v))} options={[30, 45, 60, 90, 120, 180].map(n => ({ value: String(n), label: `${n} minutes` }))} /></div>
    <fieldset className="space-y-2"><legend className="text-sm font-extrabold text-slate-900">Practice topics</legend><div className="grid gap-2 md:grid-cols-2">{topics.map(topic => { const checked = ids.includes(topic.id); return <button type="button" key={topic.id} role="checkbox" aria-checked={checked} onClick={() => setIds(previous => checked ? previous.filter(id => id !== topic.id) : [...previous, topic.id])} className={`flex items-start gap-3 rounded-xl border p-3 text-left transition-colors focus-visible:outline-2 focus-visible:outline-violet-600 ${checked ? "border-violet-300 bg-violet-50" : "border-slate-200 bg-white hover:bg-slate-50"}`}><span aria-hidden="true" className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-md border text-xs font-bold ${checked ? "border-violet-700 bg-violet-700 text-white" : "border-slate-300"}`}>{checked ? "✓" : ""}</span><span><span className="block text-sm font-bold text-slate-900">{topic.title}</span><span className="text-xs text-slate-500">{topic.category} · {topic.minutes} min</span></span></button>; })}</div></fieldset>
    <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-600">Selected topics</p><p className="text-2xl font-extrabold">{plan.selectedTopics.length}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-600">Scheduled time</p><p className="text-2xl font-extrabold">{plan.totalMinutes} min</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-600">Over capacity</p><p className="text-2xl font-extrabold">{plan.unscheduledMinutes} min</p></div></div>
    {plan.unscheduledMinutes > 0 ? <p role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950">Your selected topics exceed the available study time. Increase the horizon or daily capacity to fit everything.</p> : null}
    <div className="space-y-2"><h3 className="text-sm font-extrabold">Day-by-day schedule</h3><div className="grid gap-2 md:grid-cols-2">{plan.sessions.map(day => <div key={day.day} className="rounded-xl border border-slate-200 p-3"><p className="text-sm font-bold text-slate-900">Day {day.day} · {day.totalMinutes} min</p>{day.topics.length ? <ul className="mt-2 space-y-1">{day.topics.map(topic => <li key={topic.id} className="text-xs text-slate-600">{topic.title} — {topic.minutes} min</li>)}</ul> : <p className="mt-2 text-xs text-slate-500">Rest or independent review</p>}</div>)}</div></div>
    <div className="flex flex-wrap gap-2"><button type="button" className={action} onClick={() => download(formatPracticePlanText(plan), `${exam.toLowerCase()}-practice-plan.txt`, "text/plain;charset=utf-8")}>Download TXT</button><button type="button" className={action} onClick={() => download(formatPracticePlanCsv(plan), `${exam.toLowerCase()}-practice-plan.csv`, "text/csv;charset=utf-8")}>Download CSV</button><button type="button" className={action} onClick={() => download(JSON.stringify(plan, null, 2), `${exam.toLowerCase()}-practice-plan.json`, "application/json")}>Download JSON</button><button type="button" className={action} onClick={async () => { try { await navigator.clipboard.writeText(formatPracticePlanText(plan)); setFeedback("Practice plan copied."); } catch { setFeedback("Copy unavailable. Use a download option."); } }}>Copy plan</button></div>{feedback ? <p role="status" className="text-xs text-slate-600">{feedback}</p> : null}
  </section>;
}
