"use client";
import { useState } from "react";
import { gradePracticeSession, practiceReport, selectPracticeQuestions, type PracticeExam, type PracticeTopic } from "@/app/dashboard/test-prep/practice/question-bank";
import { ThemedExportSelect } from "@/components/shared/themed-export-select";
const button = "inline-flex min-h-10 items-center justify-center rounded-full border border-slate-200 bg-white px-4 text-xs font-bold text-slate-900 hover:border-violet-400 hover:bg-violet-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-600";
export function ExamPracticeQuiz() {
  const [exam, setExam] = useState<PracticeExam>("SAT");
  const [topic, setTopic] = useState<PracticeTopic | "All">("All");
  const [limit, setLimit] = useState(10);
  const [answers, setAnswers] = useState<Record<string, number>>({});
  const [submitted, setSubmitted] = useState(false);
  const [feedback, setFeedback] = useState("");
  const questions = selectPracticeQuestions(exam, topic, limit);
  const responses = questions.flatMap(q => Number.isInteger(answers[q.id]) ? [{ id: q.id, choice: answers[q.id] }] : []);
  const score = gradePracticeSession(questions, responses);
  function restart() { setAnswers({}); setSubmitted(false); setFeedback(""); }
  function exportReport() { const blob = new Blob([practiceReport(exam, questions, responses)], {type:"text/plain;charset=utf-8"}); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `${exam.toLowerCase()}-practice-results.txt`; document.body.appendChild(a); a.click(); a.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
  return <section aria-label="SAT and ACT practice questions" className="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
    <div><h1 className="text-2xl font-extrabold tracking-tight text-slate-950">Practice questions</h1><p className="mt-2 text-sm leading-6 text-slate-600">Original educational questions for skills practice. Not official SAT or ACT questions or a predictive exam score. Results remain in this browser session and are not saved to your account.</p></div>
    <div className="flex flex-wrap gap-2" role="group" aria-label="Exam selection">{(["SAT","ACT"] as const).map(e => <button key={e} type="button" aria-pressed={exam===e} onClick={() => {setExam(e); setTopic("All"); restart();}} className={`${button} ${exam===e ? "!border-slate-900 !bg-slate-900 !text-white" : ""}`}>{e}</button>)}</div>
    <div className="flex flex-wrap gap-4"><ThemedExportSelect name="practiceTopic" label="Topic" defaultValue="All" value={topic} onValueChange={v => {setTopic(v as PracticeTopic | "All"); restart();}} options={["All","Math","Reading","English",...(exam==="ACT" ? ["Science"] : [])].map(t=>({value:t,label:t==="All" ? "All topics" : t}))}/><ThemedExportSelect name="practiceQuestionCount" label="Question count" defaultValue="10" value={String(limit)} onValueChange={v=>{setLimit(Number(v));restart();}} options={[5,10,15,20,24].map(n=>({value:String(n),label:`Up to ${n} questions`}))}/></div>
    <p className="text-sm text-slate-600" aria-live="polite">{questions.length} questions · {score.answered} answered</p>
    <div className="space-y-4">{questions.map((q,i) => <fieldset key={q.id} disabled={submitted} className="rounded-xl border border-slate-200 p-4"><legend className="px-1 text-sm font-extrabold text-slate-900">Question {i+1} · {q.topic}</legend><p className="mb-3 text-sm leading-6 text-slate-800">{q.prompt}</p><div className="grid gap-2">{q.choices.map((choice,j) => <button key={j} type="button" role="radio" aria-checked={answers[q.id]===j} disabled={submitted} onClick={()=>setAnswers(previous=>({...previous,[q.id]:j}))} className={`flex min-h-11 items-center gap-3 rounded-xl border px-3 py-2 text-left text-sm focus-visible:outline-2 focus-visible:outline-violet-600 disabled:cursor-default ${answers[q.id]===j ? "border-violet-500 bg-violet-50 text-violet-950" : "border-slate-200 bg-white text-slate-800 hover:bg-slate-50"}`}><span aria-hidden="true" className={`flex h-5 w-5 shrink-0 items-center justify-center rounded-full border ${answers[q.id]===j ? "border-violet-600 bg-violet-600 text-white" : "border-slate-400"}`}>{answers[q.id]===j ? "✓" : ""}</span><span>{String.fromCharCode(65+j)}. {choice}</span></button>)}</div>{submitted ? <div className={`mt-3 rounded-lg p-3 text-sm ${answers[q.id]===q.correct ? "bg-emerald-50 text-emerald-950" : "bg-amber-50 text-amber-950"}`}><strong>{answers[q.id]===q.correct ? "Correct" : answers[q.id]===undefined ? "Unanswered" : "Review this answer"}</strong><p className="mt-1">Correct answer: {q.choices[q.correct]}. {q.explanation}</p></div> : null}</fieldset>)}</div>
    {submitted ? <div role="status" className="rounded-xl border border-slate-200 bg-slate-50 p-4"><h2 className="text-lg font-extrabold text-slate-950">Session results</h2><p className="mt-1 text-sm">{score.correct}/{score.total} correct ({score.percentage}%) · {score.unanswered} unanswered</p><p className="mt-1 text-xs text-slate-600">Practice percentage only; not an official scaled score.</p></div> : null}
    <div className="flex flex-wrap gap-2">{!submitted ? <button type="button" className={`${button} !border-slate-900 !bg-slate-900 !text-white`} onClick={()=>{setSubmitted(true);setFeedback("");}}>Submit answers</button> : <><button type="button" className={button} onClick={exportReport}>Download results TXT</button><button type="button" className={button} onClick={async()=>{try{await navigator.clipboard.writeText(practiceReport(exam,questions,responses));setFeedback("Results copied.");}catch{setFeedback("Copy unavailable; download the report instead.");}}}>Copy results</button></>}<button type="button" className={button} onClick={restart}>Start again</button></div>{feedback ? <p role="status" className="text-sm text-slate-600">{feedback}</p> : null}
  </section>;
}
