export type {Question,Finding} from "./shared";
export {checkMissingId} from "./missing-id";
export {checkIdFormat} from "./id-format";
export {checkMissingPrompt} from "./missing-prompt";
export {checkShortPrompt} from "./short-prompt";
export {checkMissingExplanation} from "./missing-explanation";
export {checkShortExplanation} from "./short-explanation";
export {checkChoiceCount} from "./choice-count";
export {checkBlankChoice} from "./blank-choice";
export {checkDuplicateChoices} from "./duplicate-choices";
export {checkCorrectRange} from "./correct-range";
export {checkExamValue} from "./exam-value";
export {checkTopicValue} from "./topic-value";
export {checkScienceEligibility} from "./science-eligibility";
export {checkPromptLength} from "./prompt-length";
export {checkExplanationLength} from "./explanation-length";
import type {Question,Finding} from "./shared";
import {checkMissingId} from "./missing-id";
import {checkIdFormat} from "./id-format";
import {checkMissingPrompt} from "./missing-prompt";
import {checkShortPrompt} from "./short-prompt";
import {checkMissingExplanation} from "./missing-explanation";
import {checkShortExplanation} from "./short-explanation";
import {checkChoiceCount} from "./choice-count";
import {checkBlankChoice} from "./blank-choice";
import {checkDuplicateChoices} from "./duplicate-choices";
import {checkCorrectRange} from "./correct-range";
import {checkExamValue} from "./exam-value";
import {checkTopicValue} from "./topic-value";
import {checkScienceEligibility} from "./science-eligibility";
import {checkPromptLength} from "./prompt-length";
import {checkExplanationLength} from "./explanation-length";
export function auditQuestionBank(questions:readonly Question[]):Finding[] {
 const findings:Finding[] = [];
 findings.push(...checkMissingId(questions));
 findings.push(...checkIdFormat(questions));
 findings.push(...checkMissingPrompt(questions));
 findings.push(...checkShortPrompt(questions));
 findings.push(...checkMissingExplanation(questions));
 findings.push(...checkShortExplanation(questions));
 findings.push(...checkChoiceCount(questions));
 findings.push(...checkBlankChoice(questions));
 findings.push(...checkDuplicateChoices(questions));
 findings.push(...checkCorrectRange(questions));
 findings.push(...checkExamValue(questions));
 findings.push(...checkTopicValue(questions));
 findings.push(...checkScienceEligibility(questions));
 findings.push(...checkPromptLength(questions));
 findings.push(...checkExplanationLength(questions));
 const seen=new Set<string>();
 for(const question of questions){if(seen.has(question.id))findings.push({questionId:question.id,rule:"duplicate-id",message:"Question ID is duplicated"});seen.add(question.id);}
 return findings;
}
