import { workspaceAudit } from './audit';
import { and,eq,inArray,desc } from 'drizzle-orm';
import { db } from '../client';
import { classroomAssignments,assignmentWork } from '../schema/learning-workspaces';
import { questionRevisions } from '../schema/question-bank';
import { practiceAttempts } from '../schema/practice-attempts';
import { parseQuestionContent,studentQuestion,gradeLibrarySession,type QuestionSnapshot } from '../question-bank/contract';
import { workspaceAccount,classroomAccess,requireWorkspacePermission,type WorkspaceActor } from './access';
import { workspaceText,workspaceId,dueDate,WorkspaceError,workspacePermissions } from './contract';
function snapshot(row:typeof questionRevisions.$inferSelect):QuestionSnapshot{return {...parseQuestionContent(row.content),id:row.id,entryId:row.entryId,version:row.version};}
export async function assignmentQuestionChoices(actor:WorkspaceActor){return db.transaction(async tx=>{await workspaceAccount(tx,actor);await requireWorkspacePermission(tx,actor.id,workspacePermissions.educator);const rows=await tx.select().from(questionRevisions).where(eq(questionRevisions.status,'published')).orderBy(desc(questionRevisions.createdAt)).limit(200);return rows.map(row=>studentQuestion(snapshot(row)));});}
export async function createClassroomAssignment(actor:WorkspaceActor,classroomId:unknown,title:unknown,exam:unknown,ids:unknown,due:unknown){
 if(exam!=='SAT'&&exam!=='ACT')throw new WorkspaceError('Choose SAT or ACT.');if(!Array.isArray(ids)||ids.length<1||ids.length>20||new Set(ids).size!==ids.length)throw new WorkspaceError('Choose 1-20 distinct reviewed questions.');const revisionIds=ids.map(workspaceId);const dueAt=dueDate(due);
 return db.transaction(async tx=>{await workspaceAccount(tx,actor,true);const room=await classroomAccess(tx,actor,classroomId,true);const rows=await tx.select().from(questionRevisions).where(inArray(questionRevisions.id,revisionIds)).for('share');if(rows.length!==revisionIds.length||rows.some(row=>row.status!=='published'||![exam,'Both'].includes(snapshot(row).exam)))throw new WorkspaceError('Choose published questions matching the exam.');const existing=await tx.select({id:classroomAssignments.id}).from(classroomAssignments).where(eq(classroomAssignments.classroomId,room.id));if(existing.length>=100)throw new WorkspaceError('Assignment limit reached.');const [saved]=await tx.insert(classroomAssignments).values({classroomId:room.id,title:workspaceText(title,'Assignment'),exam,revisionIds,dueAt}).returning();if(!saved)throw new WorkspaceError('Unable to create assignment.');await workspaceAudit(tx,actor,'assignment',saved.id,'create');return {success:true,id:saved.id};});
}
export async function closeClassroomAssignment(actor:WorkspaceActor,id:unknown){return db.transaction(async tx=>{await workspaceAccount(tx,actor);const [assignment]=await tx.select().from(classroomAssignments).where(eq(classroomAssignments.id,workspaceId(id)));if(!assignment)throw new WorkspaceError('Assignment unavailable.');await classroomAccess(tx,actor,assignment.classroomId,true);await tx.update(classroomAssignments).set({closedAt:new Date()}).where(eq(classroomAssignments.id,assignment.id));await workspaceAudit(tx,actor,'assignment',assignment.id,'close');return {success:true};});}
export async function assignmentSession(actor:WorkspaceActor,id:unknown,start=false){return db.transaction(async tx=>{await workspaceAccount(tx,actor);const [assignment]=await tx.select().from(classroomAssignments).where(eq(classroomAssignments.id,workspaceId(id)));if(!assignment)throw new WorkspaceError('Assignment unavailable.');await classroomAccess(tx,actor,assignment.classroomId);let [work]=await tx.select().from(assignmentWork).where(and(eq(assignmentWork.assignmentId,assignment.id),eq(assignmentWork.userId,actor.id))).for('update');const now=new Date();if(work&&!work.submittedAt&&start&&now.getTime()>work.startedAt.getTime()+4*3600000){await tx.update(assignmentWork).set({startedAt:now,draftAnswers:[]}).where(eq(assignmentWork.id,work.id));work={...work,startedAt:now,draftAnswers:[]};}if(!work?.submittedAt&&(assignment.closedAt||assignment.dueAt<=now))throw new WorkspaceError('This assignment is closed or past its due date.');if(!work&&start){[work]=await tx.insert(assignmentWork).values({assignmentId:assignment.id,userId:actor.id}).returning();}const revisions=await tx.select().from(questionRevisions).where(inArray(questionRevisions.id,assignment.revisionIds));const map=new Map(revisions.map(row=>[row.id,snapshot(row)]));return {assignment,work:work??null,expired:!!work&&!work.submittedAt&&now.getTime()>work.startedAt.getTime()+4*3600000,questions:assignment.revisionIds.map(key=>{const row=map.get(key);if(!row)throw new WorkspaceError('Assignment questions unavailable.');return studentQuestion(row);})};});}
export async function saveAssignmentWork(actor:WorkspaceActor,id:unknown,answers:unknown,submit=false){return db.transaction(async tx=>{
 await workspaceAccount(tx,actor);const [assignment]=await tx.select().from(classroomAssignments).where(eq(classroomAssignments.id,workspaceId(id)));if(!assignment)throw new WorkspaceError('Assignment unavailable.');await classroomAccess(tx,actor,assignment.classroomId);const [work]=await tx.select().from(assignmentWork).where(and(eq(assignmentWork.assignmentId,assignment.id),eq(assignmentWork.userId,actor.id))).for('update');if(!work)throw new WorkspaceError('Open the assignment first.');if(work.submittedAt)return {success:true,submitted:true,percentage:work.percentage,id:work.attemptId};const now=new Date();if(assignment.closedAt||assignment.dueAt<=now)throw new WorkspaceError('This assignment is closed or past its due date.');const revisions=(await tx.select().from(questionRevisions).where(inArray(questionRevisions.id,assignment.revisionIds))).map(snapshot);const result=gradeLibrarySession({exam:assignment.exam,revisionIds:assignment.revisionIds,createdAt:work.startedAt,expiresAt:new Date(Math.min(assignment.dueAt.getTime(),work.startedAt.getTime()+4*3600000))},revisions,answers,now);
 if(!submit){await tx.update(assignmentWork).set({draftAnswers:[...result.answers]}).where(eq(assignmentWork.id,work.id));return {success:true,saved:true};}
 const map=new Map(revisions.map(r=>[r.id,r]));const [attempt]=await tx.insert(practiceAttempts).values({userId:actor.id,exam:result.exam,total:result.total,answered:result.answered,correct:result.correct,incorrect:result.incorrect,unanswered:result.unanswered,percentage:result.percentage,durationSeconds:result.durationSeconds,questionIds:[...result.questionIds],questionSnapshots:assignment.revisionIds.map(key=>map.get(key)!),answers:[...result.answers],topicBreakdown:[...result.topicBreakdown]}).returning({id:practiceAttempts.id});if(!attempt)throw new WorkspaceError('Unable to save assignment.');await tx.update(assignmentWork).set({submittedAt:now,attemptId:attempt.id,percentage:result.percentage,draftAnswers:[]}).where(eq(assignmentWork.id,work.id));await workspaceAudit(tx,actor,'assignment',assignment.id,'submit');return {success:true,submitted:true,percentage:result.percentage,id:attempt.id};
});}
