import { workspaceAudit } from './audit';
import { randomUUID } from 'node:crypto';
import { and,eq,desc,sql } from 'drizzle-orm';
import { db } from '../client';
import { organizations,organizationMemberships } from '../schema/organizations';
import { classrooms,classroomMembers,classroomAssignments,assignmentWork,learningInvites } from '../schema/learning-workspaces';
import { users } from '../schema/users';
import { workspaceAccount,classroomAccess,requireWorkspacePermission,hasWorkspacePermission,type WorkspaceActor } from './access';
import { workspacePermissions,workspaceText,workspaceId,WorkspaceError } from './contract';
export async function createClassroom(actor:WorkspaceActor,title:unknown){return db.transaction(async tx=>{await workspaceAccount(tx,actor,true);await requireWorkspacePermission(tx,actor.id,workspacePermissions.educator);const existing=await tx.select({id:classrooms.id}).from(classrooms).where(eq(classrooms.ownerId,actor.id));if(existing.length>=25)throw new WorkspaceError('The workspace limit is 25 classrooms.');const name=workspaceText(title,'Classroom');const [org]=await tx.insert(organizations).values({name,slug:`classroom-${randomUUID()}`,type:'test_prep_center'}).returning();if(!org)throw new WorkspaceError('Unable to create workspace.');await tx.insert(organizationMemberships).values({organizationId:org.id,userId:actor.id,isOwner:true});const [room]=await tx.insert(classrooms).values({organizationId:org.id,ownerId:actor.id,title:name}).returning();if(!room)throw new WorkspaceError('Unable to create classroom.');await workspaceAudit(tx,actor,'classroom',room.id,'create');return room;});}
export async function listClassrooms(actor:WorkspaceActor){return db.transaction(async tx=>{await workspaceAccount(tx,actor);const educator=await hasWorkspacePermission(tx,actor.id,workspacePermissions.educator);const owned=educator?await tx.select({id:classrooms.id,title:classrooms.title,archivedAt:classrooms.archivedAt}).from(classrooms).innerJoin(organizations,eq(organizations.id,classrooms.organizationId)).innerJoin(organizationMemberships,and(eq(organizationMemberships.organizationId,classrooms.organizationId),eq(organizationMemberships.userId,actor.id),eq(organizationMemberships.status,'active'),eq(organizationMemberships.isOwner,true))).where(and(eq(classrooms.ownerId,actor.id),eq(organizations.isActive,true),eq(organizations.isArchived,false))).orderBy(desc(classrooms.createdAt)).limit(25):[];const joined=await tx.select({id:classrooms.id,title:classrooms.title}).from(classroomMembers).innerJoin(classrooms,eq(classrooms.id,classroomMembers.classroomId)).innerJoin(organizations,eq(organizations.id,classrooms.organizationId)).where(and(eq(classroomMembers.userId,actor.id),sql`${classrooms.archivedAt} IS NULL`,eq(organizations.isActive,true),eq(organizations.isArchived,false))).limit(100);return {educator,owned,joined};});}
export async function classroomDetail(actor:WorkspaceActor,id:string,owner=false){return db.transaction(async tx=>{await workspaceAccount(tx,actor);const room=await classroomAccess(tx,actor,id,owner);const assignments=await tx.select().from(classroomAssignments).where(eq(classroomAssignments.classroomId,room.id)).orderBy(desc(classroomAssignments.createdAt)).limit(100);const roster=owner?await tx.select({id:users.id,name:users.name,email:users.email}).from(classroomMembers).innerJoin(users,eq(users.id,classroomMembers.userId)).where(eq(classroomMembers.classroomId,room.id)).limit(100):[];const invites=owner?await tx.select({id:learningInvites.id,email:learningInvites.email,expiresAt:learningInvites.expiresAt,usedAt:learningInvites.usedAt,revokedAt:learningInvites.revokedAt}).from(learningInvites).where(eq(learningInvites.classroomId,room.id)).orderBy(desc(learningInvites.createdAt)).limit(50):[];const work=await tx.select({assignmentId:assignmentWork.assignmentId,userId:assignmentWork.userId,submittedAt:assignmentWork.submittedAt,percentage:assignmentWork.percentage}).from(assignmentWork).innerJoin(classroomAssignments,eq(classroomAssignments.id,assignmentWork.assignmentId)).innerJoin(classroomMembers,and(eq(classroomMembers.classroomId,room.id),eq(classroomMembers.userId,assignmentWork.userId))).where(and(eq(classroomAssignments.classroomId,room.id),owner?undefined:eq(assignmentWork.userId,actor.id))).limit(10000);return {room,assignments,roster,invites,work};});}
export async function manageClassroom(actor:WorkspaceActor,id:unknown,action:unknown,userId?:unknown){return db.transaction(async tx=>{await workspaceAccount(tx,actor);const room=await classroomAccess(tx,actor,id,true);if(action==='archive'){await tx.update(classrooms).set({archivedAt:new Date()}).where(eq(classrooms.id,room.id));await tx.update(learningInvites).set({revokedAt:new Date()}).where(and(eq(learningInvites.classroomId,room.id),sql`${learningInvites.usedAt} IS NULL`));}else if(action==='remove'){await tx.delete(classroomMembers).where(and(eq(classroomMembers.classroomId,room.id),eq(classroomMembers.userId,workspaceId(userId))));}else throw new WorkspaceError('Invalid classroom action.');await workspaceAudit(tx,actor,'classroom',room.id,String(action));return {success:true};});}
