import { workspaceAudit } from './audit';
import { and,eq,desc,asc,sql } from 'drizzle-orm';
import { db } from '../client';
import { supportTickets,supportMessages } from '../schema/learning-workspaces';
import { workspaceAccount,requireWorkspacePermission,hasWorkspacePermission,type WorkspaceActor,type WorkspaceTransaction } from './access';
import { workspacePermissions,workspaceText,workspaceId,supportCategory,WorkspaceError } from './contract';
async function ticketAccess(tx:WorkspaceTransaction,actor:WorkspaceActor,id:unknown,staff:boolean){if(staff)await requireWorkspacePermission(tx,actor.id,workspacePermissions.support);const [ticket]=await tx.select().from(supportTickets).where(and(eq(supportTickets.id,workspaceId(id)),staff?undefined:eq(supportTickets.userId,actor.id))).for('update');if(!ticket)throw new WorkspaceError('Ticket unavailable.');return ticket;}
export async function listSupportTickets(actor:WorkspaceActor,staff=false){return db.transaction(async tx=>{await workspaceAccount(tx,actor);if(staff)await requireWorkspacePermission(tx,actor.id,workspacePermissions.support);const canSupport=await hasWorkspacePermission(tx,actor.id,workspacePermissions.support);const tickets=await tx.select().from(supportTickets).where(staff?undefined:eq(supportTickets.userId,actor.id)).orderBy(desc(supportTickets.updatedAt)).limit(100);return {tickets,canSupport};});}
export async function createSupportTicket(actor:WorkspaceActor,subject:unknown,category:unknown,body:unknown){return db.transaction(async tx=>{await workspaceAccount(tx,actor);const recent=await tx.select({id:supportTickets.id}).from(supportTickets).where(and(eq(supportTickets.userId,actor.id),sql`${supportTickets.createdAt}>now()-interval '1 day'`));if(recent.length>=5)throw new WorkspaceError('You can open up to five tickets per day.');const [ticket]=await tx.insert(supportTickets).values({userId:actor.id,subject:workspaceText(subject,'Subject'),category:supportCategory(category)}).returning();if(!ticket)throw new WorkspaceError('Unable to open ticket.');await tx.insert(supportMessages).values({ticketId:ticket.id,authorId:actor.id,body:workspaceText(body,'Message',10,4000)});await workspaceAudit(tx,actor,'support',ticket.id,'create');return {success:true,id:ticket.id};});}
export async function supportTicketDetail(actor:WorkspaceActor,id:string,staff=false){return db.transaction(async tx=>{await workspaceAccount(tx,actor);const ticket=await ticketAccess(tx,actor,id,staff);const messages=await tx.select({id:supportMessages.id,body:supportMessages.body,createdAt:supportMessages.createdAt,authorId:supportMessages.authorId}).from(supportMessages).where(eq(supportMessages.ticketId,ticket.id)).orderBy(asc(supportMessages.createdAt)).limit(200);return {ticket,messages:messages.map(m=>({id:m.id,body:m.body,createdAt:m.createdAt,from:m.authorId===ticket.userId?'You':'Support'}))};});}
export async function replySupportTicket(actor:WorkspaceActor,id:unknown,body:unknown,staff=false){return db.transaction(async tx=>{await workspaceAccount(tx,actor);const ticket=await ticketAccess(tx,actor,id,staff);if(ticket.status==='closed')throw new WorkspaceError('Reopen this ticket before replying.');const count=await tx.select({id:supportMessages.id}).from(supportMessages).where(eq(supportMessages.ticketId,ticket.id));if(count.length>=200)throw new WorkspaceError('Conversation limit reached; open a new ticket.');const recent=await tx.select({id:supportMessages.id}).from(supportMessages).where(and(eq(supportMessages.authorId,actor.id),sql`${supportMessages.createdAt}>now()-interval '1 hour'`));if(recent.length>=30)throw new WorkspaceError('Try again in an hour.');await tx.insert(supportMessages).values({ticketId:ticket.id,authorId:actor.id,body:workspaceText(body,'Message',10,4000)});await tx.update(supportTickets).set({status:staff?'replied':'open',updatedAt:new Date()}).where(eq(supportTickets.id,ticket.id));await workspaceAudit(tx,actor,'support',ticket.id,staff?'staff-update':'customer-update');return {success:true};});}
export async function setSupportStatus(actor:WorkspaceActor,id:unknown,status:unknown,staff=false){if(status!=='open'&&status!=='closed')throw new WorkspaceError('Invalid ticket status.');return db.transaction(async tx=>{await workspaceAccount(tx,actor);const ticket=await ticketAccess(tx,actor,id,staff);await tx.update(supportTickets).set({status,updatedAt:new Date()}).where(eq(supportTickets.id,ticket.id));await workspaceAudit(tx,actor,'support',ticket.id,staff?'staff-update':'customer-update');return {success:true};});}
