/** Run only on an empty disposable database distinct from the application database. */
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { parse } from 'dotenv';
import postgres from 'postgres';
import { eq,and,sql } from 'drizzle-orm';
const directory=path.dirname(fileURLToPath(import.meta.url));
const url=process.env.SUPPORT_TEST_DATABASE_URL;if(!url)throw new Error('Set SUPPORT_TEST_DATABASE_URL to an EMPTY disposable database.');
function identity(value:string){const u=new URL(value);return `${u.hostname}:${u.port||5432}${u.pathname}`;}
let appUrl:string|undefined;try{appUrl=parse(await readFile(path.resolve(directory,'../../../../.env.local'))).DATABASE_URL;}catch{/* optional */}
if([appUrl,process.env.DATABASE_URL].some(value=>value&&identity(value)===identity(url)))throw new Error('Refusing application database.');
const bootstrap=postgres(url,{max:1,prepare:false,onnotice:()=>{}});let close:(()=>Promise<void>)|undefined;let checks=0;
function assert(ok:unknown,label:string):asserts ok{if(!ok)throw new Error(label);checks++;}
async function denied(fn:()=>Promise<unknown>,label:string){let rejected=false;try{await fn();}catch{rejected=true;}assert(rejected,label);}
try{
 const [count]=await bootstrap`select count(*)::int as n from information_schema.tables where table_schema='public'`;if(count?.n!==0)throw new Error('Test database must be empty.');
 const journal=JSON.parse(await readFile(path.resolve(directory,'../../drizzle/meta/_journal.json'),'utf8')) as {entries:{tag:string}[]};
 await bootstrap.begin(async tx=>{for(const entry of journal.entries){const source=await readFile(path.resolve(directory,`../../drizzle/${entry.tag}.sql`),'utf8');for(const statement of source.split('--> statement-breakpoint'))if(statement.trim())await tx.unsafe(statement);}});checks++;
 process.env.DATABASE_URL=url;const {db,client}=await import('../client');close=()=>client.end();const schema=await import('../schema');const {users,roles,userRoles,supportTickets}=schema;
 const {seedLearningWorkspacesRBAC}=await import('../seeds/learning-workspaces-rbac');await seedLearningWorkspacesRBAC();const w=await import('./index');
 const people=await db.insert(users).values(['customer','other','staff','staff2','teacher','teacher2'].map(name=>({name,email:`support-${name}@example.test`,emailVerifiedAt:new Date()}))).returning();
 function actor(name:string){const user=people.find(person=>person.name===name);if(!user)throw new Error('Missing fixture');return {id:user.id,authVersion:user.authVersion};}
 const customer=actor('customer'),other=actor('other'),staff=actor('staff'),staff2=actor('staff2'),teacher=actor('teacher'),teacher2=actor('teacher2');
 for(const [person,key] of [[staff,'support_workspace'],[staff2,'support_workspace'],[teacher,'educator_workspace'],[teacher2,'educator_workspace']] as const){const [role]=await db.select().from(roles).where(eq(roles.key,key));if(!role)throw new Error('Missing role');await db.insert(userRoles).values({userId:person.id,roleId:role.id});}
 const date=new Date('2026-10-01T00:00:00Z');await db.insert(supportTickets).values(Array.from({length:56},(_,i)=>({userId:customer.id,subject:`Pagination fixture ${i.toString().padStart(2,'0')}`,category:i%2?'account':'technical',status:i%3===0?'closed' as const:'open' as const,createdAt:date,updatedAt:date})));
 const [privateTicket]=await db.insert(supportTickets).values({userId:other.id,subject:'Other private ticket with hidden subject',category:'content',updatedAt:date}).returning();assert(privateTicket,'Private fixture inserted');
 const first=await w.listSupportTickets(customer);const next=await w.listSupportTickets(customer,false,{page:2});const last=await w.listSupportTickets(customer,false,{page:3});assert(first.total===56&&first.tickets.length===25&&first.pages===3,'Owner gets correct private total');assert(next.tickets.length===25&&last.tickets.length===6,'All pages available');assert(new Set([...first.tickets,...next.tickets,...last.tickets].map(t=>t.id)).size===56,'Tie-breaking prevents duplicate/missing pages');assert((await w.listSupportTickets(customer,false,{page:9999})).page===3,'Out-of-range page clamps to last page');assert((await w.listSupportTickets(customer,false,{q:'Other private'})).total===0,'Private subjects and counts do not leak through search');assert((await w.listSupportTickets(other)).total===1,'Other owner sees only own ticket');
 assert((await w.listSupportTickets(customer,false,{status:'closed'})).total===19,'Status filter');assert((await w.listSupportTickets(customer,false,{category:'account'})).total===28,'Category filter');assert((await w.listSupportTickets(customer,false,{q:'fixture 00'})).total===1,'Subject search');assert((await w.listSupportTickets(customer,false,{q:'no matching subject'})).pages===1,'Empty result pagination');await denied(()=>w.listSupportTickets(customer,true,{q:'Other private'}),'Forged staff search denied');assert((await w.listSupportTickets(staff,true)).total===57,'Scoped staff sees full inbox');
 const literal=await w.createSupportTicket(customer,'Literal 50%_ search','technical','This is an original test support message.');assert((await w.listSupportTickets(customer,false,{q:'50%_'})).total===1,'SQL search wildcards treated literally');assert((await w.supportTicketDetail(customer,literal.id)).ticket.priority==='normal','Existing/new priority default normal');
 await denied(()=>w.triageSupportTicket(customer,literal.id,'high','claim'),'Owner cannot grant self triage');await denied(()=>w.triageSupportTicket(teacher,literal.id,'high','claim'),'Educator cannot triage support');await denied(()=>w.triageSupportTicket(staff,literal.id,'critical','claim'),'Invalid priority denied');await denied(()=>w.triageSupportTicket(staff,literal.id,'high',['claim']),'Array assignment action denied');
 const claimed=await Promise.allSettled([w.triageSupportTicket(staff,literal.id,'high','claim'),w.triageSupportTicket(staff2,literal.id,'high','claim')]);assert(claimed.filter(result=>result.status==='fulfilled').length===1,'Concurrent claim has one winner');const ticket=await w.supportTicketDetail(staff,literal.id,true);const winner=ticket.ticket.assigneeId===staff.id?staff:staff2;const loser=winner.id===staff.id?staff2:staff;assert((await w.listSupportTickets(winner,true,{assignment:'mine',priority:'high'})).total===1,'Assigned-to-me plus priority filter');assert((await w.listSupportTickets(loser,true,{assignment:'mine'})).total===0,'Other staff own queue excludes claimed ticket');await denied(()=>w.triageSupportTicket(loser,literal.id,'normal','release'),'Other operator cannot release assignment');await w.triageSupportTicket(winner,literal.id,'high','release');assert((await w.listSupportTickets(staff,true,{assignment:'unassigned',priority:'high'})).total===1,'Release returns to unassigned queue');
 await w.triageSupportTicket(staff,literal.id,'high','claim');await db.update(users).set({isActive:false}).where(eq(users.id,staff.id));await w.triageSupportTicket(staff2,literal.id,'high','claim');assert((await w.supportTicketDetail(staff2,literal.id,true)).ticket.assigneeId===staff2.id,'Inactive assignee can be reclaimed');await db.update(users).set({isActive:true}).where(eq(users.id,staff.id));await db.delete(userRoles).where(eq(userRoles.userId,staff2.id));await w.triageSupportTicket(staff,literal.id,'high','claim');assert((await w.supportTicketDetail(staff,literal.id,true)).ticket.assigneeId===staff.id,'Revoked assignee can be reclaimed');await denied(()=>w.triageSupportTicket(staff2,literal.id,'normal','keep'),'Revoked operator cannot triage');assert((await w.listSupportTickets(staff,true,{sort:'priority'})).tickets[0]?.id===literal.id,'High priority sorts first');assert((await w.listSupportTickets(customer,false,{assignment:'mine'})).total===57,'Customer assignment filter cannot change ownership scope');
 await denied(()=>db.update(supportTickets).set({priority:'critical' as 'normal'}).where(eq(supportTickets.id,literal.id)),'SQL priority constraint');
 const room=await w.createClassroom(teacher,'Restoration classroom');assert(room,'Classroom created');const invite=await w.createLearningInvite(teacher,'classroom','support-customer@example.test',room.id);await w.acceptLearningInvite(customer,invite.token);const pending=await w.createLearningInvite(teacher,'classroom','support-other@example.test',room.id);await w.manageClassroom(teacher,room.id,'archive');await denied(()=>w.classroomDetail(customer,room.id),'Archive blocks learner');await denied(()=>w.manageClassroom(teacher2,room.id,'restore'),'Cross-tenant restore denied');await denied(()=>w.manageClassroom(customer,room.id,'restore'),'Learner restore denied');await w.manageClassroom(teacher,room.id,'restore');assert((await w.classroomDetail(customer,room.id)).room.archivedAt===null,'Owner restores existing roster access');await denied(()=>w.acceptLearningInvite(other,pending.token),'Restore does not reactivate revoked code');
 await db.update(schema.organizations).set({isActive:false}).where(eq(schema.organizations.id,room.organizationId));await denied(()=>w.manageClassroom(teacher,room.id,'restore'),'Inactive organization restore denied');
 const audits=await db.select().from(schema.auditLogs).where(and(sql`${schema.auditLogs.entityType}='workspace.support'`,sql`${schema.auditLogs.metadata}->>'operation'='triage'`));assert(audits.length>=4&&audits.every(event=>Object.keys(event.metadata??{}).length===1),'Triage audit has redacted operation metadata');
 console.log(`Support PostgreSQL acceptance passed: ${checks} checks; fixtures remain in the disposable database.`);
}catch(error){console.error(error instanceof Error?error.message:'Support acceptance failed');process.exitCode=1;}finally{if(close)await close();await bootstrap.end();}
