/** Execute only against a separate, empty, disposable PostgreSQL database. */
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { parse } from 'dotenv';
import postgres from 'postgres';
import { eq } from 'drizzle-orm';
const directory=path.dirname(fileURLToPath(import.meta.url));
const testUrl=process.env.WORKSPACE_TEST_DATABASE_URL;
if(!testUrl)throw new Error('Set WORKSPACE_TEST_DATABASE_URL to a separate EMPTY disposable database.');
function identity(url:string){const u=new URL(url);return `${u.hostname}:${u.port||5432}${u.pathname}`;}
let appUrl:string|undefined;try{appUrl=parse(await readFile(path.resolve(directory,'../../../../.env.local'))).DATABASE_URL;}catch{/* optional */}
if([appUrl,process.env.DATABASE_URL].some(url=>url&&identity(url)===identity(testUrl)))throw new Error('Refusing application database.');
const bootstrap=postgres(testUrl,{max:1,prepare:false,onnotice:()=>{}});let close:(()=>Promise<void>)|undefined;let checks=0;
function assert(ok:unknown,label:string):asserts ok{if(!ok)throw new Error(label);checks++;}
async function denied(fn:()=>Promise<unknown>,label:string){let rejected=false;try{await fn();}catch{rejected=true;}assert(rejected,label);}
try{
 const [count]=await bootstrap`select count(*)::int as n from information_schema.tables where table_schema='public'`;if(count?.n!==0)throw new Error('Disposable database must be empty.');
 const journal=JSON.parse(await readFile(path.resolve(directory,'../../drizzle/meta/_journal.json'),'utf8')) as {entries:{tag:string}[]};
 await bootstrap.begin(async tx=>{for(const entry of journal.entries){const migration=await readFile(path.resolve(directory,`../../drizzle/${entry.tag}.sql`),'utf8');for(const statement of migration.split('--> statement-breakpoint'))if(statement.trim())await tx.unsafe(statement);}});checks++;
 process.env.DATABASE_URL=testUrl;const {db,client}=await import('../client');close=()=>client.end();
 const schema=await import('../schema');const {users,roles,userRoles,practiceAttempts,classroomMembers,learningInvites,assignmentWork}=schema;
 const {seedLearningWorkspacesRBAC}=await import('../seeds/learning-workspaces-rbac');const {seedQuestionBankRBAC}=await import('../seeds/question-bank-rbac');
 const w=await import('./index');const bank=await import('../question-bank');
 const fixture=await db.insert(users).values(['teacher','teacher2','student','other','parent','support','author','reviewer','unverified'].map(name=>({name,email:`workspace-${name}@example.test`,emailVerifiedAt:name==='unverified'?null:new Date()}))).returning();
 function actor(name:string){const user=fixture.find(u=>u.name===name);if(!user)throw new Error('Fixture missing');return {id:user.id,authVersion:user.authVersion};}
 const teacher=actor('teacher'),teacher2=actor('teacher2'),student=actor('student'),other=actor('other'),parent=actor('parent'),support=actor('support'),author=actor('author'),reviewer=actor('reviewer'),unverified=actor('unverified');
 await seedLearningWorkspacesRBAC();await seedLearningWorkspacesRBAC();await seedQuestionBankRBAC();assert((await db.select().from(userRoles)).length===0,'Seeds never grant user privileges');
 for(const [person,key] of [[teacher,'educator_workspace'],[teacher2,'educator_workspace'],[support,'support_workspace'],[author,'question_author'],[reviewer,'question_reviewer']] as const){const [role]=await db.select().from(roles).where(eq(roles.key,key));if(!role)throw new Error('Role missing');await db.insert(userRoles).values({userId:person.id,roleId:role.id});}
 await denied(()=>w.createClassroom(student,'Unauthorized class'),'Student cannot create classroom');await denied(()=>w.createClassroom({...teacher,authVersion:99},'Stale account'),'Revoked session denied');
 const room=await w.createClassroom(teacher,'Acceptance classroom');assert(room,'Classroom created');const second=await w.createClassroom(teacher2,'Other tenant classroom');assert(second,'Second tenant created');
 assert((await w.listClassrooms(student)).owned.length===0,'Student cannot list educator rooms');await denied(()=>w.classroomDetail(teacher2,room.id,true),'Cross-tenant owner read denied');await denied(()=>w.classroomDetail(student,room.id),'Uninvited student denied');
 const invite=await w.createLearningInvite(teacher,'classroom','workspace-student@example.test',room.id);assert(invite.token.length===64,'Strong invitation code');const [stored]=await db.select().from(learningInvites).where(eq(learningInvites.id,invite.id!));assert(stored?.tokenHash!==invite.token,'Only hash stored');await denied(()=>w.acceptLearningInvite(other,invite.token),'Wrong recipient denied');await denied(()=>w.acceptLearningInvite(unverified,invite.token),'Unverified recipient denied');await w.acceptLearningInvite(student,invite.token);assert((await w.listClassrooms(student)).joined.length===1,'Recipient joins classroom');await denied(()=>w.acceptLearningInvite(student,invite.token),'Replay denied');await denied(()=>w.classroomDetail(student,second.id),'Student cross-tenant read denied');
 const revoked=await w.createLearningInvite(teacher,'classroom','workspace-other@example.test',room.id);await w.revokeLearningInvite(teacher,revoked.id);await denied(()=>w.acceptLearningInvite(other,revoked.token),'Revoked invitation denied');
 const content={exam:'Both',topic:'Math',difficulty:'foundation',prompt:'What is the sum of four and five?',choices:['8','9','10'],correct:1,explanation:'Adding four and five gives nine in total.',source:'Original isolated acceptance fixture.'};
 const revision=await bank.createQuestionDraft(author.id,{slug:'workspace-fixture',content});await bank.transitionQuestionRevision(author.id,revision.id,'submit','');await bank.transitionQuestionRevision(reviewer.id,revision.id,'publish','Verified answer and original provenance.');
 await denied(()=>w.createClassroomAssignment(teacher2,room.id,'Cross tenant','SAT',[revision.id],new Date(Date.now()+86400000).toISOString()),'Cross-tenant assignment denied');
 const assignment=await w.createClassroomAssignment(teacher,room.id,'Math practice','SAT',[revision.id],new Date(Date.now()+86400000).toISOString());assert(assignment.id,'Assignment created');const id=assignment.id;
 const before=await w.assignmentSession(student,id);assert(before.work===null,'GET-style read does not start assignment');await denied(()=>w.assignmentSession(other,id,true),'Unauthorized start denied');const session=await w.assignmentSession(student,id,true);assert(session.work&&!JSON.stringify(session.questions).includes('"correct"'),'Started session omits answer keys');
 await w.saveAssignmentWork(student,id,[{questionId:revision.id,choice:1}]);assert((await w.assignmentSession(student,id)).work?.draftAnswers.length===1,'Draft resumes');await denied(()=>w.saveAssignmentWork(student,id,[{questionId:revision.id,choice:1},{questionId:revision.id,choice:0}]),'Duplicate answer denied');
 const replacement=await bank.createQuestionDraft(author.id,{entryId:revision.entryId,content:{...content,correct:0,explanation:'Replacement acceptance fixture uses a different answer key.'}});await bank.transitionQuestionRevision(author.id,replacement.id,'submit','');await bank.transitionQuestionRevision(reviewer.id,replacement.id,'publish','Verified replacement fixture content.');
 const [saved,retry]=await Promise.all([w.saveAssignmentWork(student,id,[{questionId:revision.id,choice:1}],true),w.saveAssignmentWork(student,id,[],true)]);assert('percentage' in saved&&saved.percentage===100,'Pinned retired revision grades original answer');assert('id' in saved&&'id' in retry&&saved.id===retry.id,'Concurrent submission idempotent');assert((await db.select().from(practiceAttempts).where(eq(practiceAttempts.userId,student.id))).length===1,'Only one saved attempt');
 const educatorData=await w.classroomDetail(teacher,room.id,true);assert(educatorData.work[0]?.percentage===100&&!JSON.stringify(educatorData.work).includes('"answers"'),'Educator sees assigned score only');
 const parentInvite=await w.createLearningInvite(student,'parent','workspace-parent@example.test');await denied(()=>w.acceptLearningInvite(other,parentInvite.token),'Parent invite bound to recipient');await w.acceptLearningInvite(parent,parentInvite.token);let sharing=await w.parentSharing(parent);assert(sharing.summaries[0]?.attempts===1&&sharing.summaries[0]?.average===100,'Parent sees scoped summary');assert(!JSON.stringify(sharing).includes('"answers"')&&!JSON.stringify(sharing).includes('workspace-student@example.test'),'Parent projection excludes answers and student email');assert((await w.parentSharing(other)).summaries.length===0,'Other account sees no summaries');await denied(()=>w.removeParentLink(other,sharing.summaries[0]!.id),'Unauthorized revoke denied');await w.removeParentLink(student,sharing.summaries[0]!.id);sharing=await w.parentSharing(parent);assert(sharing.summaries.length===0,'Student revocation effective immediately');
 const ticket=await w.createSupportTicket(student,'Test support ticket','technical','My practice page does not load correctly.');await denied(()=>w.supportTicketDetail(other,ticket.id),'Other user cannot read ticket');await denied(()=>w.supportTicketDetail(teacher,ticket.id,true),'Educator role cannot read support tickets');await denied(()=>w.listSupportTickets(other,true),'Forged staff flag denied');assert((await w.listSupportTickets(support,true)).tickets.length===1,'Scoped support inbox works');await w.replySupportTicket(support,ticket.id,'Please reload and describe the error shown.',true);assert((await w.supportTicketDetail(student,ticket.id)).ticket.status==='replied','Staff reply visible to owner');await w.setSupportStatus(student,ticket.id,'closed');await denied(()=>w.replySupportTicket(student,ticket.id,'This is a new customer reply.'),'Closed ticket blocks reply');await w.setSupportStatus(student,ticket.id,'open');await w.replySupportTicket(student,ticket.id,'The page loads correctly after reloading.');assert((await w.supportTicketDetail(student,ticket.id)).messages.length===3,'Reopened conversation continues');
 const pending=await w.createClassroomAssignment(teacher,room.id,'Second assignment','SAT',[replacement.id],new Date(Date.now()+86400000).toISOString());assert(pending.id,'Second assignment');await w.assignmentSession(student,pending.id,true);await db.update(assignmentWork).set({startedAt:new Date(Date.now()-5*3600000)}).where(eq(assignmentWork.assignmentId,pending.id));await denied(()=>w.saveAssignmentWork(student,pending.id,[],true),'Expired work rejected');await w.assignmentSession(student,pending.id,true);assert((await w.assignmentSession(student,pending.id)).work!.startedAt.getTime()>Date.now()-60000,'Explicit restart refreshes expired session');await w.closeClassroomAssignment(teacher,pending.id);await denied(()=>w.saveAssignmentWork(student,pending.id,[],true),'Closed assignment rejects submission');
 await w.manageClassroom(teacher,room.id,'remove',student.id);await denied(()=>w.assignmentSession(student,id),'Removed learner loses access');assert((await db.select().from(classroomMembers).where(eq(classroomMembers.userId,student.id))).length===0,'Roster removal persisted');
 await w.manageClassroom(teacher,room.id,'archive');await denied(()=>w.classroomDetail(teacher,room.id,true),'Archived room inaccessible');await db.update(users).set({isActive:false}).where(eq(users.id,support.id));await denied(()=>w.listSupportTickets(support,true),'Inactive support account denied');
 // Verify the full allowed roster/assignment report cannot silently truncate work after 2,000 rows.
 const learners=await db.insert(users).values(Array.from({length:21},(_,i)=>({name:`Report learner ${i}`,email:`report-${i}@example.test`,emailVerifiedAt:new Date()}))).returning({id:users.id});
 await db.insert(classroomMembers).values(learners.map(person=>({classroomId:second.id,userId:person.id})));
 const reportAssignments=await db.insert(schema.classroomAssignments).values(Array.from({length:100},(_,i)=>({classroomId:second.id,title:`Report assignment ${i}`,exam:'SAT' as const,revisionIds:[replacement.id],dueAt:new Date(Date.now()+86400000)}))).returning({id:schema.classroomAssignments.id});
 await db.insert(assignmentWork).values(reportAssignments.flatMap(a=>learners.map(person=>({assignmentId:a.id,userId:person.id}))));
 const report=await w.classroomDetail(teacher2,second.id,true);assert(report.work.length===2100,'Report includes work beyond 2,000 records');
 const {classroomGradebook}=await import('./reports');assert(classroomGradebook(report).split('\r\n').length===2102,'Gradebook includes every allowed roster/assignment pair');
 const {sql}=await import('drizzle-orm');const audits=await db.select().from(schema.auditLogs).where(sql`${schema.auditLogs.entityType} LIKE 'workspace.%'`);assert(audits.length>=10&&audits.every(event=>event.metadata&&Object.keys(event.metadata).length===1&&typeof event.metadata.operation==='string'),'Workspace audit excludes invitation codes, emails, answers and message text');
 console.log(`Workspace PostgreSQL workflow passed: ${checks} checks. Fixtures are confined to the disposable database.`);
}catch(error){console.error(error instanceof Error?error.message:'Workspace verification failed');process.exitCode=1;}finally{if(close)await close();await bootstrap.end();}
