import { dashboardAction } from '@/components/shared/dashboard-action-styles';
import Link from 'next/link';
import { listClassrooms } from '@education/database/learning-workspaces';
import { workspaceSession } from '@/lib/workspaces';
import { WorkspaceLayout } from '@/components/workspaces/workspace-layout';
import { WorkspaceForm } from '@/components/workspaces/workspace-form';
import { Panel } from '@/components/app-shell/dashboard-ui';
export const metadata={title:'Learning workspaces',robots:{index:false,follow:false}};
export default async function Page(){const {user,actor}=await workspaceSession();const data=await listClassrooms(actor);return <WorkspaceLayout user={user} title="Learning workspaces" description="Join a classroom, complete original practice assignments, and manage private sharing."><Panel title="Your classrooms">{data.joined.length?data.joined.map(room=><Link key={room.id} href={`/dashboard/workspaces/classrooms/${room.id}`} className="mb-3 block rounded-2xl border border-[#dfe0d5] bg-white p-4 font-bold">{room.title}</Link>):<p className="text-sm text-slate-500">No classrooms yet. Accept an invitation from your educator.</p>}</Panel>{data.educator?<><Panel title="Educator classrooms">{data.owned.map(room=><div key={room.id} className="mb-3 rounded-2xl border border-[#dfe0d5] bg-white p-4">{room.archivedAt?<div><p className="mb-3">{room.title} · Archived</p><WorkspaceForm action="classroom.restore" values={{id:room.id}} label="Restore classroom"/></div>:<Link className={dashboardAction} href={`/dashboard/workspaces/educator/${room.id}`}>{room.title}</Link>}</div>)}</Panel><Panel title="Create a classroom" description="Each classroom has its own private roster and assignments."><WorkspaceForm action="classroom.create" fields={[{name:'title',label:'Classroom name'}]} label="Create classroom"/></Panel></>:<Panel title="Educator access"><p className="text-sm text-slate-600">An administrator must assign the Educator workspace role before you can create classrooms.</p></Panel>}</WorkspaceLayout>;}
